#!/usr/bin/env python3
"""homerealm — a self-hosted, Realm-style panel for Minecraft Bedrock worlds.

Runs each world as its own always-on container (itzg/minecraft-bedrock-server),
managed from a small web panel: create (presets/seed/flat), clone, settings,
player permissions, start/stop, delete-to-archive.

Configuration is via environment variables (see README / .env.example).
No auth by design — expose only on your LAN or a VPN (e.g. Tailscale).
"""
import datetime, json, os, re, subprocess
from pathlib import Path
from flask import Flask, request, redirect, Response, jsonify

__version__ = "0.1.0"

# ---------- configuration ----------
DATA = Path(os.environ.get("DATA_DIR", "/data"))          # inside this container
HOST_DATA = os.environ.get("HOST_DATA_DIR", "/volume1/docker/homerealm")
PUID = os.environ.get("PUID", "1000")
PGID = os.environ.get("PGID", "100")
PANEL_PORT = int(os.environ.get("PANEL_PORT", "8090"))
BASE_PORT = int(os.environ.get("BASE_PORT", "19132"))     # first world port
REMOTE_ADDRESS = os.environ.get("REMOTE_ADDRESS", "")     # shown as "away" address
BEDROCK_IMAGE = os.environ.get("BEDROCK_IMAGE", "itzg/minecraft-bedrock-server:latest")
PROJECT = "homerealm-worlds"                               # compose project name

# Optional LAN auto-discovery (macvlan): each world gets its own LAN IP on the
# default Bedrock port so consoles/tablets list it under "LAN Games".
DISCOVERY = os.environ.get("DISCOVERY_ENABLED", "false").lower() == "true"
MACVLAN_NETWORK = os.environ.get("MACVLAN_NETWORK", "mcnet")
WORLD_IP_PREFIX = os.environ.get("WORLD_IP_PREFIX", "192.168.1.")
WORLD_IP_FIRST = int(os.environ.get("WORLD_IP_FIRST", "250"))
WORLD_IP_LAST = int(os.environ.get("WORLD_IP_LAST", "254"))

WORLDS = DATA / "worlds.json"
COMPOSE = DATA / "docker-compose.yml"
DIFFS = ["peaceful", "easy", "normal", "hard"]
MODES = ["survival", "creative", "adventure"]
PERMS = ["visitor", "member", "operator"]
PRESETS = {
    "survival-easy":     {"label": "Survival (easy)",   "mode": "survival",  "difficulty": "easy",     "cheats": False},
    "survival-peaceful": {"label": "Peaceful survival", "mode": "survival",  "difficulty": "peaceful", "cheats": False},
    "survival-hard":     {"label": "Hard survival",     "mode": "survival",  "difficulty": "hard",     "cheats": False},
    "creative":          {"label": "Creative sandbox",  "mode": "creative",  "difficulty": "peaceful", "cheats": True},
    "adventure":         {"label": "Adventure",         "mode": "adventure", "difficulty": "normal",   "cheats": False},
}
DEFAULTS = {"difficulty": "easy", "cheats": False, "max_players": 10,
            "view_distance": 10, "seed": "", "level_type": "DEFAULT",
            "default_permission": "member"}

app = Flask(__name__)

# ---------- model ----------
def load():
    return json.loads(WORLDS.read_text()) if WORLDS.exists() else []

def save(ws):
    WORLDS.write_text(json.dumps(ws, indent=1))

def status(name):
    r = subprocess.run(["docker", "inspect", "-f", "{{.State.Status}}", f"mc-{name}"],
                       capture_output=True, text=True)
    return r.stdout.strip() if r.returncode == 0 else "stopped"

def regen():
    lines = ["# GENERATED by homerealm — edit via the panel or CLI, not by hand.",
             "services:"]
    for w in load():
        env = {"EULA": "TRUE", "VERSION": "LATEST", "SERVER_NAME": w["name"],
               "GAMEMODE": w["mode"], "DIFFICULTY": w["difficulty"],
               "LEVEL_NAME": w["name"], "ALLOW_CHEATS": str(w["cheats"]).lower(),
               "ALLOW_LIST": "false", "MAX_PLAYERS": w["max_players"],
               "VIEW_DISTANCE": w["view_distance"],
               "DEFAULT_PLAYER_PERMISSION_LEVEL": w["default_permission"]}
        if w.get("seed"):
            env["LEVEL_SEED"] = w["seed"]
        if w.get("level_type", "DEFAULT") != "DEFAULT":
            env["LEVEL_TYPE"] = w["level_type"]
        envs = ", ".join(f'{k}: "{v}"' for k, v in env.items())
        net = (f'\n    networks: {{ default: {{}}, {MACVLAN_NETWORK}: '
               f'{{ ipv4_address: "{w["ip"]}" }} }}') if DISCOVERY and w.get("ip") else ""
        lines += [f'''  mc-{w["name"]}:
    image: {BEDROCK_IMAGE}
    container_name: mc-{w["name"]}
    restart: unless-stopped
    environment: {{ {envs} }}
    ports: ["{w["port"]}:19132/udp"]{net}
    volumes: ["{HOST_DATA}/{w["name"]}:/data"]''']
    if DISCOVERY:
        lines += ["networks:", f"  {MACVLAN_NETWORK}: {{ external: true }}"]
    COMPOSE.write_text("\n".join(lines) + "\n")

def compose(*args):
    r = subprocess.run(["docker", "compose", "-p", PROJECT, "-f", str(COMPOSE)]
                       + list(args), capture_output=True, text=True)
    if r.returncode != 0:
        print(f"compose {args} failed: {r.stderr[-500:]}", flush=True)
    return r

def alloc(ws):
    """Next free port and (if discovery) LAN IP."""
    port = max([w["port"] for w in ws] + [BASE_PORT - 1]) + 1
    ip = None
    if DISCOVERY:
        used = [int(w["ip"].rsplit(".", 1)[1]) for w in ws if w.get("ip")]
        octet = max(used + [WORLD_IP_FIRST - 1]) + 1
        if octet > WORLD_IP_LAST:
            return None, None
        ip = f"{WORLD_IP_PREFIX}{octet}"
    return port, ip

def own(path):
    subprocess.run(["chown", "-R", f"{PUID}:{PGID}", str(path)])
    subprocess.run(["chmod", "-R", "u+rwX,g+rwX", str(path)])

def seen_players(name):
    """Merge players from container logs into a persistent per-world roster."""
    roster_f = DATA / name / "players_seen.json"
    roster = json.loads(roster_f.read_text()) if roster_f.exists() else {}
    logs = subprocess.run(["docker", "logs", f"mc-{name}"],
                          capture_output=True, text=True).stdout
    for m in re.finditer(r"Player connected: ([^,]+), xuid: (\d+)", logs):
        roster[m.group(2)] = m.group(1).strip()
    try:
        roster_f.write_text(json.dumps(roster))
    except OSError:
        pass
    return roster

def permissions(name):
    f = DATA / name / "permissions.json"
    try:
        return {e["xuid"]: e["permission"] for e in json.loads(f.read_text())}
    except Exception:
        return {}

def set_permission(name, xuid, level):
    f = DATA / name / "permissions.json"
    perms = permissions(name)
    if level == "member":
        perms.pop(xuid, None)
    else:
        perms[xuid] = level
    f.write_text(json.dumps([{"permission": v, "xuid": k} for k, v in perms.items()],
                            indent=1))

# ---------- JSON API (used by the CLI) ----------
@app.get("/api/worlds")
def api_worlds():
    return jsonify([{**w, "status": status(w["name"])} for w in load()])

@app.get("/api/version")
def api_version():
    return jsonify({"version": __version__})

# ---------- HTML ----------
PAGE = """<!doctype html><html><head><meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1">
<title>homerealm</title>
<style>
 body {{ font-family: -apple-system, sans-serif; max-width: 660px; margin: 2rem auto;
        padding: 0 1rem; background: #f0f4e8; color: #2d3a2e; }}
 h1 {{ font-size: 1.6rem; }} .world {{ background: white; border-radius: 12px;
   padding: 1rem 1.2rem; margin: .8rem 0; box-shadow: 0 1px 4px rgba(0,0,0,.1); }}
 .running {{ border-left: 6px solid #5cb85c; }}
 .stopped, .exited, .created, .absent {{ border-left: 6px solid #ccc; }}
 .addr {{ font-family: ui-monospace, monospace; background: #eef; padding: 2px 6px;
   border-radius: 6px; }} button {{ border: 0; border-radius: 8px; padding: .5rem .9rem;
   margin-right: .4rem; cursor: pointer; font-size: .9rem; }}
 .del {{ background: #fdd; }} .go {{ background: #cfc; }} .neutral {{ background: #eee; }}
 form.inline {{ display: inline; }} .newbox {{ background: #e2ecd8; border-radius: 12px;
   padding: 1rem 1.2rem; margin-top: 1.4rem; }} input, select {{ padding: .4rem;
   border-radius: 8px; border: 1px solid #aaa; font-size: .95rem; margin: 2px; }}
 .meta {{ color: #667; font-size: .85rem; }} details {{ margin-top: .6rem; }}
 summary {{ cursor: pointer; color: #464; font-size: .9rem; }}
 table {{ border-collapse: collapse; margin: .4rem 0; }} td {{ padding: 2px 8px 2px 0; }}
 .settings label {{ font-size: .85rem; margin-right: .6rem; white-space: nowrap; }}
 footer {{ margin-top: 2rem; }}
</style></head><body>
<h1>&#9968; homerealm</h1>
{worlds}
<div class="newbox"><b>New world</b>
 <form method="post" action="/new">
  <input name="name" placeholder="world-name" pattern="[a-z0-9-]{{1,20}}" required>
  <select name="preset">{preset_opts}</select>
  <input name="seed" placeholder="seed (optional)" size="12">
  <label><input type="checkbox" name="flat"> flat</label>
  <button class="go" type="submit">Create</button>
 </form>
 <div class="meta">lowercase letters, numbers, dashes &middot; ready in ~30s</div>
</div>
<p class="meta">{discovery_note} Settings and permission changes apply with a
~20s world restart.</p>
<footer class="meta">homerealm v{version} &middot;
<a href="https://github.com/rosskukulinski/homerealm">github</a></footer>
</body></html>"""

WORLD_TPL = """<div class="world {status}">
 <b>{name}</b> <span class="meta">&middot; {mode} &middot; {difficulty} &middot; {status}</span><br>
 <span class="meta">{addr_line}</span><br><br>
 {startstop}
 <form class="inline" method="post" action="/restart/{name}"><button class="neutral">Restart</button></form>
 <form class="inline" method="post" action="/clone/{name}"
   onsubmit="var n=prompt('Name for the copy:','{name}-copy');if(!n)return false;this.newname.value=n.trim().toLowerCase();return true;">
   <input type="hidden" name="newname"><button class="neutral">Clone</button></form>
 <form class="inline" method="post" action="/delete/{name}"
   onsubmit="return confirm('Delete world {name}? (data is archived, not destroyed)')">
   <button class="del">Delete</button></form>
 <details class="settings"><summary>Settings</summary>
  <form method="post" action="/settings/{name}">
   <label>mode <select name="mode">{mode_opts}</select></label>
   <label>difficulty <select name="difficulty">{diff_opts}</select></label>
   <label>cheats <select name="cheats">{cheat_opts}</select></label><br>
   <label>max players <input name="max_players" type="number" min="1" max="30" value="{max_players}" style="width:4em"></label>
   <label>view distance <input name="view_distance" type="number" min="5" max="32" value="{view_distance}" style="width:4em"></label>
   <label>new players are <select name="default_permission">{perm_opts}</select></label>
   <button class="go" type="submit">Apply (restarts world)</button>
  </form></details>
 <details><summary>Players</summary>{players}</details>
</div>"""

def opts(values, current):
    return "".join(f'<option{" selected" if v == str(current) else ""}>{v}</option>'
                   for v in values)

def players_html(name):
    roster, perms = seen_players(name), permissions(name)
    if not roster:
        return '<p class="meta">No one has joined yet — players appear here after their first visit.</p>'
    rows = ""
    for xuid, tag in sorted(roster.items(), key=lambda kv: kv[1].lower()):
        level = perms.get(xuid, "member")
        rows += (f'<tr><td><b>{tag}</b></td><td>'
                 f'<form class="inline" method="post" action="/permission/{name}">'
                 f'<input type="hidden" name="xuid" value="{xuid}">'
                 f'<select name="level">{opts(PERMS, level)}</select> '
                 f'<button class="neutral">Set</button></form></td></tr>')
    return f"<table>{rows}</table>"

@app.get("/")
def index():
    blocks = ""
    for w in load():
        st = status(w["name"])
        ss = (f'<form class="inline" method="post" action="/stop/{w["name"]}"><button class="neutral">Stop</button></form>'
              if st == "running" else
              f'<form class="inline" method="post" action="/start/{w["name"]}"><button class="go">Start</button></form>')
        addr = f'connect: <span class="addr">{REMOTE_ADDRESS or "&lt;host&gt;"}:{w["port"]}</span>'
        if DISCOVERY and w.get("ip"):
            addr = "home: auto (LAN Games) &middot; away: " + addr.replace("connect: ", "")
        blocks += WORLD_TPL.format(
            name=w["name"], mode=w["mode"], difficulty=w["difficulty"], status=st,
            addr_line=addr, startstop=ss,
            mode_opts=opts(MODES, w["mode"]), diff_opts=opts(DIFFS, w["difficulty"]),
            cheat_opts=opts(["false", "true"], str(w["cheats"]).lower()),
            perm_opts=opts(PERMS, w["default_permission"]),
            max_players=w["max_players"], view_distance=w["view_distance"],
            players=players_html(w["name"]))
    preset_opts = "".join(f'<option value="{k}">{v["label"]}</option>'
                          for k, v in PRESETS.items())
    note = ("Running worlds appear automatically under Friends &rarr; LAN Games "
            "on devices in the same network." if DISCOVERY else
            "Add worlds on devices via Servers &rarr; Add Server with the address shown.")
    return Response(PAGE.format(worlds=blocks or "<p>No worlds yet — make one below!</p>",
                                preset_opts=preset_opts, discovery_note=note,
                                version=__version__), mimetype="text/html")

@app.post("/new")
def new():
    ws = load()
    name = request.form["name"].strip().lower()
    preset = PRESETS.get(request.form.get("preset", ""))
    mode = preset["mode"] if preset else request.form.get("mode", "survival")
    if not re.fullmatch(r"[a-z0-9-]{1,20}", name) or mode not in MODES:
        return "bad name/mode", 400
    if any(w["name"] == name for w in ws):
        return "world exists", 409
    port, ip = alloc(ws)
    if port is None:
        return "no free world IPs — raise WORLD_IP_LAST", 507
    w = {"name": name, "port": port, "mode": mode, "ip": ip, **DEFAULTS,
         "seed": request.form.get("seed", "").strip(),
         "level_type": "FLAT" if request.form.get("flat") else "DEFAULT"}
    if preset:
        w.update(difficulty=preset["difficulty"], cheats=preset["cheats"])
    elif mode == "creative":
        w.update(difficulty="peaceful", cheats=True)
    d = DATA / name
    d.mkdir(exist_ok=True)
    own(d)
    save(ws + [w]); regen(); compose("up", "-d", f"mc-{name}")
    return redirect("/")

@app.post("/settings/<name>")
def settings(name):
    ws = load()
    for w in ws:
        if w["name"] == name:
            mode = request.form.get("mode", w["mode"])
            diff = request.form.get("difficulty", w["difficulty"])
            perm = request.form.get("default_permission", w["default_permission"])
            if mode not in MODES or diff not in DIFFS or perm not in PERMS:
                return "bad value", 400
            w.update(mode=mode, difficulty=diff, default_permission=perm,
                     cheats=request.form.get("cheats") == "true",
                     max_players=max(1, min(30, int(request.form.get("max_players", 10)))),
                     view_distance=max(5, min(32, int(request.form.get("view_distance", 10)))))
            save(ws); regen(); compose("up", "-d", f"mc-{name}")
            return redirect("/")
    return "no such world", 404

@app.post("/permission/<name>")
def permission(name):
    if not any(w["name"] == name for w in load()):
        return "no such world", 404
    xuid, level = request.form["xuid"], request.form["level"]
    if not re.fullmatch(r"\d{5,20}", xuid) or level not in PERMS:
        return "bad value", 400
    set_permission(name, xuid, level)
    subprocess.run(["docker", "restart", f"mc-{name}"], capture_output=True)
    return redirect("/")

@app.post("/clone/<name>")
def clone(name):
    import shutil
    ws = load()
    src = next((w for w in ws if w["name"] == name), None)
    if not src:
        return "no such world", 404
    newname = request.form.get("newname", "").strip().lower()
    if not re.fullmatch(r"[a-z0-9-]{1,20}", newname):
        return "bad name", 400
    if any(w["name"] == newname for w in ws):
        return "world exists", 409
    port, ip = alloc(ws)
    if port is None:
        return "no free world IPs — raise WORLD_IP_LAST", 507
    was_running = status(name) == "running"
    if was_running:                      # cold copy: leveldb hates live copies
        subprocess.run(["docker", "stop", f"mc-{name}"], capture_output=True)
    shutil.copytree(DATA / name, DATA / newname)
    old_world = DATA / newname / "worlds" / name
    if old_world.exists():
        old_world.rename(DATA / newname / "worlds" / newname)
    own(DATA / newname)
    if was_running:
        subprocess.run(["docker", "start", f"mc-{name}"], capture_output=True)
    w = {**src, "name": newname, "port": port, "ip": ip}
    save(ws + [w]); regen(); compose("up", "-d", f"mc-{newname}")
    return redirect("/")

@app.post("/delete/<name>")
def delete(name):
    ws = load()
    keep = [w for w in ws if w["name"] != name]
    if len(keep) == len(ws):
        return "no such world", 404
    compose("rm", "-sf", f"mc-{name}")
    arch = DATA / "_archive"
    arch.mkdir(exist_ok=True)
    (DATA / name).rename(arch / f"{name}-{datetime.datetime.now():%Y%m%d-%H%M}")
    save(keep); regen()
    return redirect("/")

@app.post("/start/<name>")
def start(name):
    subprocess.run(["docker", "start", f"mc-{name}"], capture_output=True)
    return redirect("/")

@app.post("/stop/<name>")
def stop(name):
    subprocess.run(["docker", "stop", f"mc-{name}"], capture_output=True)
    return redirect("/")

@app.post("/restart/<name>")
def restart(name):
    subprocess.run(["docker", "restart", f"mc-{name}"], capture_output=True)
    return redirect("/")

if __name__ == "__main__":
    app.run(host="0.0.0.0", port=PANEL_PORT)
