// homerealm — a self-hosted, Realm-style panel for Minecraft Bedrock worlds,
// Tailscale-native.
//
// The panel is a tsnet application: it joins your tailnet as its own node
// (no tailscaled needed on the host) and serves HTTP/HTTPS there directly.
// Each world runs as its own itzg/minecraft-bedrock-server container wrapped
// in a tailscale/tailscale sidecar, so every world is its own tailnet node
// (mc-<name>) answering on the default Bedrock port.
//
// Configuration is via environment variables (see README / .env.example).
// Access control is your tailnet's ACLs — the panel itself has no login.
package main

import (
	"context"
	"encoding/json"
	"errors"
	"fmt"
	"html/template"
	"log"
	"net/http"
	"os"
	"os/exec"
	"path/filepath"
	"regexp"
	"sort"
	"strconv"
	"strings"
	"sync"
	"time"

	"tailscale.com/client/local"
	"tailscale.com/tsnet"
)

const appVersion = "0.2.0"

// ---------- configuration ----------
var (
	dataDir  = getenv("DATA_DIR", "/data") // inside this container
	hostData = getenv("HOST_DATA_DIR", "/volume1/docker/homerealm")
	puid     = getenv("PUID", "1000")
	pgid     = getenv("PGID", "100")

	panelPort = getenvInt("PANEL_PORT", 8090) // LAN listener (optional)
	panelLAN  = getenvBool("PANEL_LISTEN_LAN", true)
	basePort  = getenvInt("BASE_PORT", 19132) // first world's LAN UDP port

	tsHostname     = getenv("TS_HOSTNAME", "homerealm") // panel's tailnet name
	tsAuthKey      = os.Getenv("TS_AUTHKEY")
	bedrockImage   = getenv("BEDROCK_IMAGE", "itzg/minecraft-bedrock-server:latest")
	tailscaleImage = getenv("TAILSCALE_IMAGE", "tailscale/tailscale:latest")

	// Optional LAN auto-discovery (macvlan): each world also gets its own LAN
	// IP on the default Bedrock port so consoles/tablets without Tailscale
	// list it under "LAN Games".
	discovery      = getenvBool("DISCOVERY_ENABLED", false)
	macvlanNetwork = getenv("MACVLAN_NETWORK", "mcnet")
	worldIPPrefix  = getenv("WORLD_IP_PREFIX", "192.168.1.")
	worldIPFirst   = getenvInt("WORLD_IP_FIRST", 250)
	worldIPLast    = getenvInt("WORLD_IP_LAST", 254)
)

const project = "homerealm-worlds" // compose project name

var (
	worldsFile  = filepath.Join(dataDir, "worlds.json")
	composeFile = filepath.Join(dataDir, "docker-compose.yml")
	tsStateRoot = filepath.Join(dataDir, "_tailscale")
)

var (
	diffs = []string{"peaceful", "easy", "normal", "hard"}
	modes = []string{"survival", "creative", "adventure"}
	perms = []string{"visitor", "member", "operator"}

	nameRe = regexp.MustCompile(`^[a-z0-9-]{1,20}$`)
	xuidRe = regexp.MustCompile(`^\d{5,20}$`)
)

type preset struct {
	Key, Label, Mode, Difficulty string
	Cheats                       bool
}

var presets = []preset{
	{"survival-easy", "Survival (easy)", "survival", "easy", false},
	{"survival-peaceful", "Peaceful survival", "survival", "peaceful", false},
	{"survival-hard", "Hard survival", "survival", "hard", false},
	{"creative", "Creative sandbox", "creative", "peaceful", true},
	{"adventure", "Adventure", "adventure", "normal", false},
}

// ---------- model ----------
type world struct {
	Name              string `json:"name"`
	Port              int    `json:"port"`
	Mode              string `json:"mode"`
	IP                string `json:"ip,omitempty"` // macvlan LAN IP (discovery)
	Difficulty        string `json:"difficulty"`
	Cheats            bool   `json:"cheats"`
	MaxPlayers        int    `json:"max_players"`
	ViewDistance      int    `json:"view_distance"`
	Seed              string `json:"seed"`
	LevelType         string `json:"level_type"`
	DefaultPermission string `json:"default_permission"`
}

func defaultWorld(name string, port int, ip, mode string) world {
	return world{Name: name, Port: port, Mode: mode, IP: ip,
		Difficulty: "easy", MaxPlayers: 10, ViewDistance: 10,
		LevelType: "DEFAULT", DefaultPermission: "member"}
}

var mu sync.Mutex // serializes mutations of worlds.json + compose state

func load() []world {
	b, err := os.ReadFile(worldsFile)
	if err != nil {
		return nil
	}
	var ws []world
	if err := json.Unmarshal(b, &ws); err != nil {
		log.Printf("worlds.json unreadable: %v", err)
		return nil
	}
	return ws
}

func save(ws []world) {
	b, _ := json.MarshalIndent(ws, "", " ")
	if err := os.WriteFile(worldsFile, b, 0o644); err != nil {
		log.Printf("save worlds.json: %v", err)
	}
}

func worldStatus(name string) string {
	out, err := exec.Command("docker", "inspect", "-f", "{{.State.Status}}", "mc-"+name).Output()
	if err != nil {
		return "stopped"
	}
	return strings.TrimSpace(string(out))
}

// regen rewrites the generated compose file: per world, a tailscale/tailscale
// sidecar (the world's tailnet node, mc-<name>) plus the Bedrock server
// sharing its network namespace.
func regen() {
	var b strings.Builder
	b.WriteString("# GENERATED by homerealm — edit via the panel or CLI, not by hand.\nservices:\n")
	for _, w := range load() {
		env := [][2]string{
			{"EULA", "TRUE"}, {"VERSION", "LATEST"}, {"SERVER_NAME", w.Name},
			{"GAMEMODE", w.Mode}, {"DIFFICULTY", w.Difficulty},
			{"LEVEL_NAME", w.Name}, {"ALLOW_CHEATS", strconv.FormatBool(w.Cheats)},
			{"ALLOW_LIST", "false"}, {"MAX_PLAYERS", strconv.Itoa(w.MaxPlayers)},
			{"VIEW_DISTANCE", strconv.Itoa(w.ViewDistance)},
			{"DEFAULT_PLAYER_PERMISSION_LEVEL", w.DefaultPermission},
		}
		if w.Seed != "" {
			env = append(env, [2]string{"LEVEL_SEED", w.Seed})
		}
		if w.LevelType != "" && w.LevelType != "DEFAULT" {
			env = append(env, [2]string{"LEVEL_TYPE", w.LevelType})
		}
		var envs []string
		for _, kv := range env {
			envs = append(envs, fmt.Sprintf("%s: %q", kv[0], fmt.Sprint(kv[1])))
		}
		net := ""
		if discovery && w.IP != "" {
			net = fmt.Sprintf("\n    networks: { default: {}, %s: { ipv4_address: %q } }",
				macvlanNetwork, w.IP)
		}
		fmt.Fprintf(&b, `  ts-%[1]s:
    image: %[2]s
    container_name: ts-%[1]s
    hostname: mc-%[1]s
    restart: unless-stopped
    environment: { TS_AUTHKEY: "${TS_AUTHKEY}", TS_STATE_DIR: "/var/lib/tailscale", TS_USERSPACE: "false", TS_AUTH_ONCE: "true" }
    devices: ["/dev/net/tun"]
    cap_add: ["NET_ADMIN"]
    volumes: ["%[3]s/_tailscale/%[1]s:/var/lib/tailscale"]
    ports: ["%[4]d:19132/udp"]%[5]s
  mc-%[1]s:
    image: %[6]s
    container_name: mc-%[1]s
    restart: unless-stopped
    network_mode: "service:ts-%[1]s"
    depends_on: [ts-%[1]s]
    environment: { %[7]s }
    volumes: ["%[3]s/%[1]s:/data"]
`, w.Name, tailscaleImage, hostData, w.Port, net, bedrockImage, strings.Join(envs, ", "))
	}
	if discovery {
		fmt.Fprintf(&b, "networks:\n  %s: { external: true }\n", macvlanNetwork)
	}
	if err := os.WriteFile(composeFile, []byte(b.String()), 0o644); err != nil {
		log.Printf("write compose: %v", err)
	}
}

func compose(args ...string) {
	cmd := exec.Command("docker", append([]string{"compose", "-p", project, "-f", composeFile}, args...)...)
	out, err := cmd.CombinedOutput()
	if err != nil {
		s := string(out)
		if len(s) > 500 {
			s = s[len(s)-500:]
		}
		log.Printf("compose %v failed: %s", args, s)
	}
}

func docker(args ...string) {
	if err := exec.Command("docker", args...).Run(); err != nil {
		log.Printf("docker %v: %v", args, err)
	}
}

// alloc picks the next free LAN port and (if discovery) LAN IP.
func alloc(ws []world) (port int, ip string, ok bool) {
	port = basePort - 1
	for _, w := range ws {
		if w.Port > port {
			port = w.Port
		}
	}
	port++
	if discovery {
		octet := worldIPFirst - 1
		for _, w := range ws {
			if w.IP == "" {
				continue
			}
			if i := strings.LastIndex(w.IP, "."); i >= 0 {
				if n, err := strconv.Atoi(w.IP[i+1:]); err == nil && n > octet {
					octet = n
				}
			}
		}
		octet++
		if octet > worldIPLast {
			return 0, "", false
		}
		ip = worldIPPrefix + strconv.Itoa(octet)
	}
	return port, ip, true
}

func own(path string) {
	exec.Command("chown", "-R", puid+":"+pgid, path).Run()
	exec.Command("chmod", "-R", "u+rwX,g+rwX", path).Run()
}

var playerRe = regexp.MustCompile(`Player connected: ([^,]+), xuid: (\d+)`)

// seenPlayers merges players from container logs into a persistent per-world roster.
func seenPlayers(name string) map[string]string {
	rosterFile := filepath.Join(dataDir, name, "players_seen.json")
	roster := map[string]string{}
	if b, err := os.ReadFile(rosterFile); err == nil {
		json.Unmarshal(b, &roster)
	}
	logs, _ := exec.Command("docker", "logs", "mc-"+name).Output()
	for _, m := range playerRe.FindAllStringSubmatch(string(logs), -1) {
		roster[m[2]] = strings.TrimSpace(m[1])
	}
	if b, err := json.Marshal(roster); err == nil {
		os.WriteFile(rosterFile, b, 0o644)
	}
	return roster
}

func permissions(name string) map[string]string {
	var entries []struct{ Permission, Xuid string }
	b, err := os.ReadFile(filepath.Join(dataDir, name, "permissions.json"))
	if err != nil || json.Unmarshal(b, &entries) != nil {
		return map[string]string{}
	}
	out := map[string]string{}
	for _, e := range entries {
		out[e.Xuid] = e.Permission
	}
	return out
}

func setPermission(name, xuid, level string) {
	ps := permissions(name)
	if level == "member" {
		delete(ps, xuid)
	} else {
		ps[xuid] = level
	}
	type entry struct {
		Permission string `json:"permission"`
		Xuid       string `json:"xuid"`
	}
	var entries []entry
	for k, v := range ps {
		entries = append(entries, entry{v, k})
	}
	sort.Slice(entries, func(i, j int) bool { return entries[i].Xuid < entries[j].Xuid })
	if entries == nil {
		entries = []entry{}
	}
	b, _ := json.MarshalIndent(entries, "", " ")
	os.WriteFile(filepath.Join(dataDir, name, "permissions.json"), b, 0o644)
}

// ---------- HTML ----------
var page = template.Must(template.New("page").Funcs(template.FuncMap{
	"opts": func(values []string, current string) template.HTML {
		var b strings.Builder
		for _, v := range values {
			sel := ""
			if v == current {
				sel = " selected"
			}
			fmt.Fprintf(&b, "<option%s>%s</option>", sel, template.HTMLEscapeString(v))
		}
		return template.HTML(b.String())
	},
}).Parse(`<!doctype html><html><head><meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1">
<title>homerealm</title>
<style>
 body { font-family: -apple-system, sans-serif; max-width: 660px; margin: 2rem auto;
        padding: 0 1rem; background: #f0f4e8; color: #2d3a2e; }
 h1 { font-size: 1.6rem; } .world { background: white; border-radius: 12px;
   padding: 1rem 1.2rem; margin: .8rem 0; box-shadow: 0 1px 4px rgba(0,0,0,.1); }
 .running { border-left: 6px solid #5cb85c; }
 .stopped, .exited, .created, .absent { border-left: 6px solid #ccc; }
 .addr { font-family: ui-monospace, monospace; background: #eef; padding: 2px 6px;
   border-radius: 6px; } button { border: 0; border-radius: 8px; padding: .5rem .9rem;
   margin-right: .4rem; cursor: pointer; font-size: .9rem; }
 .del { background: #fdd; } .go { background: #cfc; } .neutral { background: #eee; }
 form.inline { display: inline; } .newbox { background: #e2ecd8; border-radius: 12px;
   padding: 1rem 1.2rem; margin-top: 1.4rem; } input, select { padding: .4rem;
   border-radius: 8px; border: 1px solid #aaa; font-size: .95rem; margin: 2px; }
 .meta { color: #667; font-size: .85rem; } details { margin-top: .6rem; }
 summary { cursor: pointer; color: #464; font-size: .9rem; }
 table { border-collapse: collapse; margin: .4rem 0; } td { padding: 2px 8px 2px 0; }
 .settings label { font-size: .85rem; margin-right: .6rem; white-space: nowrap; }
 footer { margin-top: 2rem; }
</style></head><body>
<h1>&#9968; homerealm</h1>
{{if not .Worlds}}<p>No worlds yet — make one below!</p>{{end}}
{{range .Worlds}}{{$w := .}}<div class="world {{.Status}}">
 <b>{{.Name}}</b> <span class="meta">&middot; {{.Mode}} &middot; {{.Difficulty}} &middot; {{.Status}}</span><br>
 <span class="meta">{{.AddrLine}}</span><br><br>
 {{if eq .Status "running"}}<form class="inline" method="post" action="/stop/{{.Name}}"><button class="neutral">Stop</button></form>{{else}}<form class="inline" method="post" action="/start/{{.Name}}"><button class="go">Start</button></form>{{end}}
 <form class="inline" method="post" action="/restart/{{.Name}}"><button class="neutral">Restart</button></form>
 <form class="inline" method="post" action="/clone/{{.Name}}"
   onsubmit="var n=prompt('Name for the copy:','{{.Name}}-copy');if(!n)return false;this.newname.value=n.trim().toLowerCase();return true;">
   <input type="hidden" name="newname"><button class="neutral">Clone</button></form>
 <form class="inline" method="post" action="/delete/{{.Name}}"
   onsubmit="return confirm('Delete world {{.Name}}? (data is archived, not destroyed)')">
   <button class="del">Delete</button></form>
 <details class="settings"><summary>Settings</summary>
  <form method="post" action="/settings/{{.Name}}">
   <label>mode <select name="mode">{{opts $.Modes .Mode}}</select></label>
   <label>difficulty <select name="difficulty">{{opts $.Diffs .Difficulty}}</select></label>
   <label>cheats <select name="cheats">{{opts $.Bools .CheatsStr}}</select></label><br>
   <label>max players <input name="max_players" type="number" min="1" max="30" value="{{.MaxPlayers}}" style="width:4em"></label>
   <label>view distance <input name="view_distance" type="number" min="5" max="32" value="{{.ViewDistance}}" style="width:4em"></label>
   <label>new players are <select name="default_permission">{{opts $.Perms .DefaultPermission}}</select></label>
   <button class="go" type="submit">Apply (restarts world)</button>
  </form></details>
 <details><summary>Players</summary>{{if .Players}}<table>{{range .Players}}<tr><td><b>{{.Tag}}</b></td><td><form class="inline" method="post" action="/permission/{{$w.Name}}"><input type="hidden" name="xuid" value="{{.Xuid}}"><select name="level">{{opts $.Perms .Level}}</select> <button class="neutral">Set</button></form></td></tr>{{end}}</table>{{else}}<p class="meta">No one has joined yet — players appear here after their first visit.</p>{{end}}</details>
</div>
{{end}}<div class="newbox"><b>New world</b>
 <form method="post" action="/new">
  <input name="name" placeholder="world-name" pattern="[a-z0-9-]{1,20}" required>
  <select name="preset">{{range .Presets}}<option value="{{.Key}}">{{.Label}}</option>{{end}}</select>
  <input name="seed" placeholder="seed (optional)" size="12">
  <label><input type="checkbox" name="flat"> flat</label>
  <button class="go" type="submit">Create</button>
 </form>
 <div class="meta">lowercase letters, numbers, dashes &middot; ready in ~30s &middot; joins your tailnet as <span class="addr">mc-&lt;name&gt;</span></div>
</div>
<p class="meta">{{.DiscoveryNote}} Settings and permission changes apply with a
~20s world restart.</p>
<footer class="meta">homerealm v{{.Version}}{{if .Identity}} &middot; {{.Identity}} via Tailscale{{end}} &middot;
<a href="https://github.com/rosskukulinski/homerealm">github</a></footer>
</body></html>`))

type playerView struct{ Xuid, Tag, Level string }

type worldView struct {
	world
	Status    string
	CheatsStr string
	AddrLine  template.HTML
	Players   []playerView
}

type pageView struct {
	Worlds                     []worldView
	Presets                    []preset
	Modes, Diffs, Perms, Bools []string
	DiscoveryNote, Version     string
	Identity                   string
}

var localClient *local.Client // set once tsnet is up; nil until then

func identity(r *http.Request) string {
	if localClient == nil {
		return ""
	}
	ctx, cancel := context.WithTimeout(r.Context(), 2*time.Second)
	defer cancel()
	who, err := localClient.WhoIs(ctx, r.RemoteAddr)
	if err != nil || who.UserProfile == nil {
		return "" // LAN visitor, or lookup failed
	}
	return who.UserProfile.LoginName
}

func playersOf(name string) []playerView {
	roster, ps := seenPlayers(name), permissions(name)
	var out []playerView
	for xuid, tag := range roster {
		level := ps[xuid]
		if level == "" {
			level = "member"
		}
		out = append(out, playerView{Xuid: xuid, Tag: tag, Level: level})
	}
	sort.Slice(out, func(i, j int) bool {
		return strings.ToLower(out[i].Tag) < strings.ToLower(out[j].Tag)
	})
	return out
}

func index(w http.ResponseWriter, r *http.Request) {
	if r.URL.Path != "/" {
		http.NotFound(w, r)
		return
	}
	view := pageView{Presets: presets, Modes: modes, Diffs: diffs, Perms: perms,
		Bools: []string{"false", "true"}, Version: appVersion, Identity: identity(r)}
	for _, wd := range load() {
		addr := fmt.Sprintf(`tailnet: <span class="addr">mc-%[1]s</span> &middot; LAN: <span class="addr">&lt;host&gt;:%[2]d</span>`,
			wd.Name, wd.Port)
		if discovery && wd.IP != "" {
			addr = "home: auto (LAN Games) &middot; " + addr
		}
		view.Worlds = append(view.Worlds, worldView{
			world: wd, Status: worldStatus(wd.Name),
			CheatsStr: strconv.FormatBool(wd.Cheats),
			AddrLine:  template.HTML(addr), Players: playersOf(wd.Name)})
	}
	if discovery {
		view.DiscoveryNote = "Running worlds appear automatically under Friends → LAN Games on devices in the same network."
	} else {
		view.DiscoveryNote = "On Tailscale devices, add worlds via Servers → Add Server with address mc-<name>, port 19132."
	}
	w.Header().Set("Content-Type", "text/html; charset=utf-8")
	if err := page.Execute(w, view); err != nil {
		log.Printf("render: %v", err)
	}
}

// ---------- JSON API (used by the CLI) ----------
func apiWorlds(w http.ResponseWriter, _ *http.Request) {
	type wireWorld struct {
		world
		Status  string `json:"status"`
		Tailnet string `json:"tailnet"`
	}
	out := []wireWorld{}
	for _, wd := range load() {
		out = append(out, wireWorld{wd, worldStatus(wd.Name), "mc-" + wd.Name})
	}
	w.Header().Set("Content-Type", "application/json")
	json.NewEncoder(w).Encode(out)
}

func apiVersion(w http.ResponseWriter, _ *http.Request) {
	w.Header().Set("Content-Type", "application/json")
	json.NewEncoder(w).Encode(map[string]string{"version": appVersion})
}

// ---------- actions ----------
func findWorld(ws []world, name string) *world {
	for i := range ws {
		if ws[i].Name == name {
			return &ws[i]
		}
	}
	return nil
}

// back redirects like the Flask app did (302 — the CLI greps for it).
func back(w http.ResponseWriter, r *http.Request) {
	http.Redirect(w, r, "/", http.StatusFound)
}

func newWorld(w http.ResponseWriter, r *http.Request) {
	mu.Lock()
	defer mu.Unlock()
	ws := load()
	name := strings.ToLower(strings.TrimSpace(r.FormValue("name")))
	var pre *preset
	for i := range presets {
		if presets[i].Key == r.FormValue("preset") {
			pre = &presets[i]
		}
	}
	mode := r.FormValue("mode")
	if pre != nil {
		mode = pre.Mode
	} else if mode == "" {
		mode = "survival"
	}
	if !nameRe.MatchString(name) || !contains(modes, mode) {
		http.Error(w, "bad name/mode", 400)
		return
	}
	if findWorld(ws, name) != nil {
		http.Error(w, "world exists", 409)
		return
	}
	port, ip, ok := alloc(ws)
	if !ok {
		http.Error(w, "no free world IPs — raise WORLD_IP_LAST", 507)
		return
	}
	wd := defaultWorld(name, port, ip, mode)
	wd.Seed = strings.TrimSpace(r.FormValue("seed"))
	if r.FormValue("flat") != "" {
		wd.LevelType = "FLAT"
	}
	if pre != nil {
		wd.Difficulty, wd.Cheats = pre.Difficulty, pre.Cheats
	} else if mode == "creative" {
		wd.Difficulty, wd.Cheats = "peaceful", true
	}
	d := filepath.Join(dataDir, name)
	os.MkdirAll(d, 0o775)
	own(d)
	os.MkdirAll(filepath.Join(tsStateRoot, name), 0o700)
	save(append(ws, wd))
	regen()
	compose("up", "-d", "mc-"+name)
	back(w, r)
}

func settings(w http.ResponseWriter, r *http.Request) {
	mu.Lock()
	defer mu.Unlock()
	ws := load()
	name := r.PathValue("name")
	wd := findWorld(ws, name)
	if wd == nil {
		http.Error(w, "no such world", 404)
		return
	}
	mode := formOr(r, "mode", wd.Mode)
	diff := formOr(r, "difficulty", wd.Difficulty)
	perm := formOr(r, "default_permission", wd.DefaultPermission)
	if !contains(modes, mode) || !contains(diffs, diff) || !contains(perms, perm) {
		http.Error(w, "bad value", 400)
		return
	}
	wd.Mode, wd.Difficulty, wd.DefaultPermission = mode, diff, perm
	wd.Cheats = r.FormValue("cheats") == "true"
	wd.MaxPlayers = clamp(formInt(r, "max_players", 10), 1, 30)
	wd.ViewDistance = clamp(formInt(r, "view_distance", 10), 5, 32)
	save(ws)
	regen()
	compose("up", "-d", "mc-"+name)
	back(w, r)
}

func permission(w http.ResponseWriter, r *http.Request) {
	mu.Lock()
	defer mu.Unlock()
	name := r.PathValue("name")
	if findWorld(load(), name) == nil {
		http.Error(w, "no such world", 404)
		return
	}
	xuid, level := r.FormValue("xuid"), r.FormValue("level")
	if !xuidRe.MatchString(xuid) || !contains(perms, level) {
		http.Error(w, "bad value", 400)
		return
	}
	setPermission(name, xuid, level)
	docker("restart", "mc-"+name)
	back(w, r)
}

func clone(w http.ResponseWriter, r *http.Request) {
	mu.Lock()
	defer mu.Unlock()
	ws := load()
	name := r.PathValue("name")
	src := findWorld(ws, name)
	if src == nil {
		http.Error(w, "no such world", 404)
		return
	}
	newname := strings.ToLower(strings.TrimSpace(r.FormValue("newname")))
	if !nameRe.MatchString(newname) {
		http.Error(w, "bad name", 400)
		return
	}
	if findWorld(ws, newname) != nil {
		http.Error(w, "world exists", 409)
		return
	}
	port, ip, ok := alloc(ws)
	if !ok {
		http.Error(w, "no free world IPs — raise WORLD_IP_LAST", 507)
		return
	}
	wasRunning := worldStatus(name) == "running"
	if wasRunning { // cold copy: leveldb hates live copies
		docker("stop", "mc-"+name)
	}
	if err := os.CopyFS(filepath.Join(dataDir, newname), os.DirFS(filepath.Join(dataDir, name))); err != nil {
		log.Printf("clone copy: %v", err)
	}
	oldWorld := filepath.Join(dataDir, newname, "worlds", name)
	if _, err := os.Stat(oldWorld); err == nil {
		os.Rename(oldWorld, filepath.Join(dataDir, newname, "worlds", newname))
	}
	own(filepath.Join(dataDir, newname))
	if wasRunning {
		docker("start", "mc-"+name)
	}
	wd := *src
	wd.Name, wd.Port, wd.IP = newname, port, ip
	os.MkdirAll(filepath.Join(tsStateRoot, newname), 0o700) // fresh tailnet identity
	save(append(ws, wd))
	regen()
	compose("up", "-d", "mc-"+newname)
	back(w, r)
}

func deleteWorld(w http.ResponseWriter, r *http.Request) {
	mu.Lock()
	defer mu.Unlock()
	ws := load()
	name := r.PathValue("name")
	if findWorld(ws, name) == nil {
		http.Error(w, "no such world", 404)
		return
	}
	var keep []world
	for _, wd := range ws {
		if wd.Name != name {
			keep = append(keep, wd)
		}
	}
	compose("rm", "-sf", "mc-"+name, "ts-"+name)
	arch := filepath.Join(dataDir, "_archive")
	os.MkdirAll(arch, 0o775)
	stamp := time.Now().Format("20060102-1504")
	if err := os.Rename(filepath.Join(dataDir, name), filepath.Join(arch, name+"-"+stamp)); err != nil {
		log.Printf("archive %s: %v", name, err)
	}
	// Drop the world's tailnet identity; the node goes offline and can be
	// removed from the admin console (a restored world re-auths as new).
	os.RemoveAll(filepath.Join(tsStateRoot, name))
	if keep == nil {
		keep = []world{}
	}
	save(keep)
	regen()
	back(w, r)
}

func start(w http.ResponseWriter, r *http.Request) {
	docker("start", "ts-"+r.PathValue("name"), "mc-"+r.PathValue("name"))
	back(w, r)
}

func stop(w http.ResponseWriter, r *http.Request) {
	docker("stop", "mc-"+r.PathValue("name")) // sidecar stays up; node stays reachable
	back(w, r)
}

func restart(w http.ResponseWriter, r *http.Request) {
	docker("restart", "mc-"+r.PathValue("name"))
	back(w, r)
}

// ---------- helpers ----------
func getenv(k, def string) string {
	if v := os.Getenv(k); v != "" {
		return v
	}
	return def
}

func getenvInt(k string, def int) int {
	if n, err := strconv.Atoi(os.Getenv(k)); err == nil {
		return n
	}
	return def
}

func getenvBool(k string, def bool) bool {
	switch strings.ToLower(os.Getenv(k)) {
	case "true", "1", "yes":
		return true
	case "false", "0", "no":
		return false
	}
	return def
}

func contains(xs []string, s string) bool {
	for _, x := range xs {
		if x == s {
			return true
		}
	}
	return false
}

func formOr(r *http.Request, key, def string) string {
	if v := r.FormValue(key); v != "" {
		return v
	}
	return def
}

func formInt(r *http.Request, key string, def int) int {
	if n, err := strconv.Atoi(r.FormValue(key)); err == nil {
		return n
	}
	return def
}

func clamp(n, lo, hi int) int {
	return max(lo, min(hi, n))
}

// ---------- main ----------
func routes() *http.ServeMux {
	mux := http.NewServeMux()
	mux.HandleFunc("GET /", index)
	mux.HandleFunc("GET /api/worlds", apiWorlds)
	mux.HandleFunc("GET /api/version", apiVersion)
	mux.HandleFunc("POST /new", newWorld)
	mux.HandleFunc("POST /settings/{name}", settings)
	mux.HandleFunc("POST /permission/{name}", permission)
	mux.HandleFunc("POST /clone/{name}", clone)
	mux.HandleFunc("POST /delete/{name}", deleteWorld)
	mux.HandleFunc("POST /start/{name}", start)
	mux.HandleFunc("POST /stop/{name}", stop)
	mux.HandleFunc("POST /restart/{name}", restart)
	return mux
}

func main() {
	log.SetFlags(log.LstdFlags)
	for _, d := range []string{dataDir, tsStateRoot, filepath.Join(tsStateRoot, "panel")} {
		if err := os.MkdirAll(d, 0o755); err != nil {
			log.Fatalf("mkdir %s: %v", d, err)
		}
	}
	mux := routes()

	// Optional plain-HTTP LAN listener (for the CLI and non-Tailscale devices
	// at home). The tailnet is the primary, authenticated front door.
	if panelLAN {
		go func() {
			log.Printf("panel (LAN) listening on :%d", panelPort)
			if err := http.ListenAndServe(fmt.Sprintf(":%d", panelPort), mux); err != nil {
				log.Printf("LAN listener: %v", err)
			}
		}()
	}

	ts := &tsnet.Server{
		Hostname: tsHostname,
		Dir:      filepath.Join(tsStateRoot, "panel"),
		AuthKey:  tsAuthKey,
		UserLogf: log.Printf,
		Logf:     func(string, ...any) {}, // quiet the debug firehose
	}
	defer ts.Close()

	var err error
	localClient, err = ts.LocalClient()
	if err != nil {
		log.Fatalf("tsnet local client: %v", err)
	}

	go func() {
		ctx, cancel := context.WithTimeout(context.Background(), 5*time.Minute)
		defer cancel()
		st, err := ts.Up(ctx)
		if err != nil {
			log.Printf("tailnet not up yet: %v (if there's a login URL above, open it)", err)
			return
		}
		log.Printf("panel on your tailnet: https://%s", strings.TrimSuffix(st.Self.DNSName, "."))
	}()

	// HTTPS with automatic Tailscale certs, HTTP alongside for tailnets
	// without HTTPS enabled.
	go func() {
		ln, err := ts.ListenTLS("tcp", ":443")
		if err != nil {
			log.Printf("tailnet HTTPS unavailable: %v", err)
			return
		}
		if err := http.Serve(ln, mux); err != nil {
			log.Printf("tailnet HTTPS listener: %v", err)
		}
	}()
	ln, err := ts.Listen("tcp", ":80")
	if err != nil {
		log.Fatalf("tsnet listen: %v", err)
	}
	if err := http.Serve(ln, mux); err != nil && !errors.Is(err, http.ErrServerClosed) {
		log.Fatalf("tailnet listener: %v", err)
	}
}
